apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: pawsible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: 268015775379.dkr.ecr.us-east-1.amazonaws.com/pawsible/discovery-server:1.0.0
        ports:
        - containerPort: 8761
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: pawsible
spec:
  selector:
    app: discovery-server
  ports:
  - port: 8761
    targetPort: 8761
