resources:
  - namespace.yaml
  - config-server.yaml
  - discovery-server.yaml
  - api-gateway.yaml
  - customers-service.yaml
  - vets-service.yaml
  - visits-service.yaml
  - admin-server.yaml
  - genai-service.yaml
