{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pawsible-services
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    app: pawsible-services
    version: {{ .Chart.AppVersion }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels: {}
  endpoints:
  - path: {{ .Values.serviceMonitor.path }}
    port: http
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
